server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

zuul:
  #Service will be mapped under the /api URI
  prefix: /api
#  Uncomment to disable auto-registering all services read from Eureka
#  ignoredServices: '*'
  routes:
    test:
      path: /redirect/**
      url: http://google.com
    student-by-address:
      path: /student-by-address/**
      url: http://localhost:9098
    student-by-service:
      path: /student-by-service/**
      serviceId: STUDENT-SERVICE
    static:
      path: /static/**

spring:
  application:
    name: zuul-server